platform :ios, "8.0"
pod 'FastCoding'
pod 'MBProgressHUD'
pod 'UIColor+MLPFlatColors'

target 'ExamSchedulingTests', :exclusive => true do
    pod 'FastCoding'
    pod 'OCMock'
end

inhibit_all_warnings!